{{- if .Values.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-certificate
  namespace: {{ .Values.namespaceOverride }}
spec:
  secretName: {{ .Values.tls.secretName }}
  dnsNames:
{{- range .Values.routes }}
{{- if not (empty .hostName) }}
    - {{ .hostName }}
{{- end }}
{{- end }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end -}}